---
  header_logo_url: /images/logo.png
  header_logo_text: "Curculionidae of the World Online"

  header_links:
    - label: Home
      link: /


    - label: Entiminae
      link: /otus/712818/overview

    - label: News
      link: /news


    - label: Search DwC
      link: /resources/tw/filter/dwc_otus

    - label: Bibliography
      link: /resources/tw/filter/bibliography

    - label: About
      link: /about
