taxa_page:
  overview:
    panels:
      - - - panel:gallery
          - panel:nomenclature
          - panel:nomenclature-references
          - panel:type
          - panel:type-specimen

        - - panel:map
          - panel:descendants
          - panel:content
          - panel:keys
          - panel:statistics
          - panel:sounds

      - - - panel:biological-associations

  specimen_records:
    rank_group: ['SpeciesGroup']
    panels:
      - - - panel:specimen-records
      - - - panel:field-occurrences

  inaturalist:
    label: 'iNaturalist'
    rank_group: ['GenusGroup', 'SpeciesGroup']
    panels:
      - - - id: panel:inaturalist

  GBIF:
    label: 'GBIF'
    panels:
      - - - id: panel:gbif

