taxa_page:
  overview:
    panels:
      - - - panel:gallery
          - panel:nomenclature
          - panel:nomenclature-references
          - panel:type
          - panel:type-specimen

        - - panel:map
          - panel:descendants
          - panel:content
          - panel:keys
          - panel:statistics
          - panel:sounds

  biological_associations:
    panels:
      - - - panel:biological-associations
